### ISSUE TITLE
No data received from sensor

### ISSUE THREAD

**Issue by algila** [giacomobartoli/vision-kit#1]
Many thanks for sharing. Launching the command `./custom_pikachu_detector.py`

I get the following error.
This is not an HW issue because if I run face detector it is working. I see a single frame on the monitor then stop.

btw line 15 i modify as follow. `from examples.vision.annotator import Annotator`

`./custom_pikachu_detector.py
Camera inference started
Traceback (most recent call last):
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 128, in transact
    fcntl.ioctl(self._dev, SPICOMM_IOCTL_TRANSACT, self._tbuf)
OSError: [Errno 14] Bad address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./custom_pikachu_detector.py", line 81, in main
    for f, result in enumerate(inference.run()):
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 76, in run
    yield self._engine.camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 257, in camera_inference
    return self._communicate(request).inference_result
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 143, in transact
    raise SpicommInternalError
aiy._drivers._spicomm.SpicommInternalError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./custom_pikachu_detector.py", line 121, in main
    last_time = now
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 87, in __exit__
    self.close()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 79, in close
    self._engine.stop_camera_inference()
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 263, in stop_camera_inference
    self._communicate(request)
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 189, in _communicate
    raise InferenceException(response.status.message)
aiy.vision.inference.InferenceException: StopCameraInference: Camera inference is not running.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./custom_pikachu_detector.py", line 127, in <module>
    main()
  File "./custom_pikachu_detector.py", line 123, in main
    camera.stop_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 758, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 752, in close
    raise exc
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1995, in _control_callback
    "No data recevied from sensor. Check all connections, "
picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check all connections, including the SUNNY chip on the camera board
`

**Comment by giacomobartoli** [comment]
@algila it seems to be a problem with the inference library:
`from aiy.vision.inference import CameraInference`

Could you provide your current working directory path?
All files must be in the same folder:  /home/AIY-projects/src/example/vision

**Comment by algila** [comment]
I stored both `custom_pikachu_detector.py` and `pikachu_object_detection.py` in the folder 
/home/pi/AIY-projects-python/src/examples/vision
the model `pikachu_detector.binaryproto` in the sub folder `/home/pi/AIY-projects-python/src/examples/vision/prove_OLI` modifing accordingly the path in the code
![20180817_130745](https://user-images.githubusercontent.com/23231557/44263417-2ac46500-a21f-11e8-8afc-6ac9d2de1625.jpg)

The library used are stored in the folder `/home/pi/AIY-projects-python/src/aiy` but the folder does not contain `annotator.py`
![20180817_130716](https://user-images.githubusercontent.com/23231557/44263561-b8a05000-a21f-11e8-89ca-bfcb64d72fa8.jpg)

In case should help the file `inference.py` contain hte following line:
`_SUPPORTED_FIRMWARE_VERSION = (1,0) #major, minor`

**Comment by giacomobartoli** [comment]
Just try to move the .protobinary in the same path to see what happens.
`/home/pi/AIY-projects-python/src/examples/vision`

**Comment by algila** [comment]
No, unfortunately it is not helping.
To me it is strange that in my system annotator.py is stored in the folder example, but in yours it is located within other library files.

**Comment by giacomobartoli** [comment]
@algila do you the latest image of the vision kit? It should be updated to April 2018.

**Comment by algila** [comment]
Yes, many thanks this solved. I uploaded the last SSD image 3rd August 2018.

To keep working your file with that last release it is just needed to changed the below.
```
from aiy.leds import Leds
from aiy.leds import PrivacyLeds
```
